name: hmbplayer
description: HMB Player - Melhor player de música do mundo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.4
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.13
  file_picker: ^4.5.1
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  firebase_remote_config: ^2.0.5
  firebase_storage: ^10.2.13
  # flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  get: ^4.6.1
  get_storage: ^2.0.3
  google_sign_in: ^5.3.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/bg.jpg
    - assets/audio/test.mp3

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  fullscreen: true