name: hmbplayer
description: HMB Player - Melhor player de música do mundo

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_card: ^2.0.0
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.4
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.12.2
  file: ^7.0.0
  file_picker: ^6.1.1
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_remote_config: ^4.3.3
  firebase_storage: ^11.4.1
  # flutter_launcher_icons: ^0.9.2
  flutter_lints: ^3.0.1
  get: ^4.6.3
  get_storage: ^2.0.3
  google_sign_in: ^6.1.6
  marquee: ^2.2.1
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.0+1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/bg.jpg
    - assets/images/my_playlist.jpg
    - assets/audio/test.mp3

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic


flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  fullscreen: true
