// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxMdhtFnitlMGRoOlwt7r2_LMWOkSPrhU',
    appId: '1:412948076040:web:99e3552375137c72b763bd',
    messagingSenderId: '412948076040',
    projectId: 'hmb-player',
    authDomain: 'hmb-player.firebaseapp.com',
    storageBucket: 'hmb-player.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIBrD1AaqfeLZnRAL3OCQCqry1XEbHrmo',
    appId: '1:412948076040:android:ac6081a87c907eb7b763bd',
    messagingSenderId: '412948076040',
    projectId: 'hmb-player',
    storageBucket: 'hmb-player.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNaU6joDuVWYYBKVnisM2qNhZUSyP7Pvc',
    appId: '1:412948076040:ios:8de81e848a6630b6b763bd',
    messagingSenderId: '412948076040',
    projectId: 'hmb-player',
    storageBucket: 'hmb-player.appspot.com',
    androidClientId: '412948076040-0bp3utlk73bu643c8merjfufmj08g8q4.apps.googleusercontent.com',
    iosClientId: '412948076040-qvhfrqgb4batlh9is7ld50bj5fmgsvq3.apps.googleusercontent.com',
    iosBundleId: 'br.com.hansmboron.hmbplayer',
  );
}
